services:
  normal:
    build:
      dockerfile: ./.docker/php81.Dockerfile
      context: .
    command: php /app/src/Services/PeopleDataProcessor.php

  parallel:
    build:
      dockerfile: ./.docker/php81.Dockerfile
      context: .
    command: php /app/src/Services/PeopleDataProcessorParallel.php